### ISSUE TITLE
🐛Bug: Bot doesn't accept photos as files

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#14]
**Describe the bug**
When you try to post with /sell using a file, the bot doesn't react. Something goes wrong, needs investigation

**To Reproduce**
Try selling with a file-photo, without compressing

**Expected behavior**
It should accept photos as files

**Screenshots**
![image](https://github.com/Salz0/telegram_flea/assets/76848642/4bd4d149-dae8-4901-b3d8-4009bf60191f)

**Comment by BloodyOcean** [comment]
Hi! I am willing to resolve that bug. May I take this issue?

**Comment by kamo-develop** [comment]
Hi! @Salz0 can you please assign this to me?
I suggest making the file handler and the photo handler (which is already written) separate, and putting the common code into another function.
