### ISSUE TITLE
📥 Implement Reply-Markup Buttons for a User-Friendly Experience

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#2]
Enhance user interaction by replacing text commands with intuitive action buttons. 🚀🔘

Expected Behavior:
Instead of typing commands, users can click on the keyboard buttons for common actions, making the app more user-friendly and accessible. 🤖📲

Docs: https://docs.aiogram.dev/en/latest/api/types/reply_keyboard_markup.html

Example:
https://github.com/aiogram/aiogram/blob/dev-2.x/examples/regular_keyboard_example.py

Make it simple

**Comment by Ferdinand-Ogama** [comment]
Hello @Salz0 can I work on this issue?

**Comment by Ferdinand-Ogama** [comment]
@Salz0 Honestly, I'm struggling with step 3.5, creating a virtual environment with poetry and setting up the project by adding  .env variables. 
Apologies, I am new to Python and the entire software dev ecosystem. 

Kindly guide me here or point me to materials.

**Comment by Ferdinand-Ogama** [comment]
Then, I don't know whether it's a bug or so. After installing requirements, unfortunately, the project couldn't build wheels for some dependencies.  "ERROR: Could not build wheels for aiohttp, frozenlist, multidict, yarl, which is required to install pyproject.toml-based projects."
