### ISSUE TITLE
⌨Remove Inline Button After User Interaction to Prevent Repeated Actions

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#20]
#### Issue Description 📝

Currently, after a user presses an inline button associated with a message in a channel, the button remains active. This allows for repeated actions, which is undesirable. Additionally, the message gets deleted from the channel upon successful action. The goal is to make the inline button disappear or be disabled once pressed, and to prevent further actions after a successful operation.

#### Requirements 🎯

1. **Inline Button Removal**: After a user presses the inline button, it should be removed from the message.
2. **Message Deletion**: Continue to delete the message from the channel after successful action, if that's the current desired behavior.
3. **Prevent Repeated Actions**: Once the action is successful and the message is deleted, the action should not be allowed to be repeated.

#### Acceptance Criteria ✅

- Inline button should disappear or become disabled after a user presses it.
- Message should continue to be deleted after a successful action.
- Users should not be able to perform the action again once it's been successfully executed.

#### Possible Solution 🛠️

1. Capture the callback query when the inline button is pressed.
2. Delete or disable the inline button from the message.
   ```python
   await bot.edit_message_reply_markup(
       chat_id=callback_query.message.chat.id,
       message_id=callback_query.message.message_id,
       reply_markup=None
   )

**Comment by sharktankful** [comment]
Hi, I'm brand new to contributing to open source (This may be my first one) but I would love to help you out with this. Do you just have to assign me this on your end?

**Comment by sharktankful** [comment]
> > Hi, I'm brand new to contributing to open source (This may be my first one) but I would love to help you out with this. Do you just have to assign me this on your end?
> 
> Hi, great to see you wanting to contribute😌 You can work on the issue right away, don't hesitate to create a pull request 🙏

Thanks! I'll get started on it then

**Comment by sharktankful** [comment]
Oh okay, Well Im at least glad the issue is solved
