### ISSUE TITLE
🆘 Implement a /help Command for User Guidance

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#3]
Enhance user support by implementing a /help command to provide guidance and information within the application. 🤝🆘

Users can type /help in the chat to receive a list of available commands, FAQs, and basic usage instructions, improving their understanding of the app's functionality. 💬❓

**Comment by avi-dey** [comment]
I am picking this up

**Comment by avi-dey** [comment]
you unassigned me?
