### ISSUE TITLE
🚀 Implement a Generalized Starting Message for New Users

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#4]
Create a generalized starting message that provides a warm welcome and essential information to new users. 🆕👋

It should be the answer to the /start command

**Comment by Anemaygi** [comment]
Hi, can you assign this task to me?

**Comment by Anemaygi** [comment]
Okay thank you

**Comment by Anemaygi** [comment]
Thank you! I'm going to study the code and telegram bots to try to contribute again later :)
