### ISSUE TITLE
Fallback to using basic `MemoryStorage()` when `REDIS_URL` is not entered 

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#48]
### What?
Create a condition to use `aiogram`'s `MemoryStorage()` class when the user did not input the `REDIS_URL`

### Why?
This would make it simpler for newcomers and contributors to work on the project without redundant functionality

This is easy to implement

**Comment by kamo-develop** [comment]
@Salz0 I will take up this issue
