### ISSUE TITLE
🌐 Implement Multi-Language Support for the Bot Using aiogram's Built-in i18n 🌍

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#6]
Description 📝:
Implement support for multiple languages in the bot using Aiogram's built-in i18n features. The language setting will not be interactive and will be a bot-level configuration.

Requirements 📋:
Installation: Install any necessary packages for i18n.
Configuration: Configure i18n settings in Aiogram bot.
Translations: Add translation files for supported languages.
Fallback: Ensure there's a fallback language (ENGLISH or UKRAINIAN) if the set language translation isn't available.
Acceptance Criteria 🎯:

- [ ] i18n is configured in the bot
- [ ] Translation files are added and loaded
- [ ] Bot responds in the configured language
- [ ] Fallback to a default language is implemented
- [ ] Steps for Implementation 🔨:
- [ ] Initialize i18n: Initialize i18n in the Aiogram bot project.

```python
from aiogram import Bot, types
from aiogram.dispatcher import Dispatcher
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram.contrib.middlewares.i18n import I18nMiddleware

bot = Bot(token='YOUR_BOT_TOKEN')
storage = MemoryStorage()
dp = Dispatcher(bot, storage=storage)

i18n = I18nMiddleware('bot', 'path/to/locales')
dp.middleware.setup(i18n)
```
Add Translation Files: Create .po files and automate .mo creation for supported languages in the /locales directory.

Configure Language in Bot: Set the language to be used in the bot settings, and not allow users to change it.

```python
@dp.message_handler(commands=['start'])
async def send_welcome(message: types.Message):
    await message.reply(i18n.t('bot.start_message'))
```
Test: Make sure all features work in the specified language, and a fallback language is used when necessary.

**Comment by vessaldaneshvar** [comment]
hello
I want to work this issue.
please assign this task to me.
