### ISSUE TITLE
🐞 Add Manual Ability to Cancel Selling Request for Items in Telegram Channel

### ISSUE THREAD

**Issue by Salz0** [Salz0/telegram_flea#8]
## Summary: 📝
Add a feature to the Flea Market Telegram Bot that allows users to manually cancel the selling request for items, effectively removing them from the Telegram channel.

### Details: 📚
Currently, once an item is posted for sale in the Telegram channel, it stays there indefinitely. Users should have the ability to manually remove their items from the channel, whether it's because the item was sold outside of the channel, withdrawn from sale, or for any other reason.

### Proposed Solution: 🛠
Add a /cancel [item_id] command to the bot.
When a user triggers this command, the bot should prompt for a confirmation to ensure it's not a mistake.
Upon confirmation, the bot should remove the corresponding item post from the Telegram channel.
### Acceptance Criteria: ✅

- [ ] A user can cancel a selling request by using the /cancel [item_id] command.
- [ ] A confirmation step exists to ensure items are not deleted accidentally.
- [ ] The item post is removed from the Telegram channel once the cancellation is confirmed.

### Additional Information: ℹ️
This feature adds flexibility for users in managing their selling requests and contributes to keeping the channel clean and relevant.

Thank you for considering this feature request. This will greatly enhance user autonomy and improve the overall experience in the Telegram channel. 🙏🤖🗑

**Comment by Apoorv012** [comment]
Hey @Salz0 I would like to work on this issue, Could you please assign this to me?
